import fs from 'node:fs';
import path from 'node:path';

const RD = path.join('public', '_redirects');
const OUT = path.join('src', 'redirects.generated.mjs');
const content = fs.readFileSync(RD, 'utf-8');

const map = {};
for (const line of content.split('\n')) {
  const s = line.trim();
  if (!s || s.startsWith('#')) continue;
  const parts = s.split(/\s+/);
  if (parts.length < 2) continue;
  const src = parts[0];
  const dst = parts[1];
  map[src] = dst;
  // Add no-extension variants for .html URLs
  if (src.endsWith('.html')) {
    const noExt = src.slice(0, -5);
    if (!map[noExt]) map[noExt] = dst;
    if (!map[noExt + '/']) map[noExt + '/'] = dst;
  }
}
const count = Object.keys(map).length;
console.log(`[embed_redirects] ${count} redirects → ${OUT}`);

let body = '// AUTO-GENERATED by scripts/embed_redirects.mjs — DO NOT EDIT\n';
body += 'export const REDIRECTS_MAP = ' + JSON.stringify(map, null, 2) + ';\n';
body += '\nexport function matchRedirect(path) {\n';
body += '  if (REDIRECTS_MAP[path]) return REDIRECTS_MAP[path];\n';
body += '  if (REDIRECTS_MAP[path + "/"]) return REDIRECTS_MAP[path + "/"];\n';
body += '  if (path.endsWith("/") && REDIRECTS_MAP[path.slice(0, -1)]) return REDIRECTS_MAP[path.slice(0, -1)];\n';
body += '  return null;\n';
body += '}\n';

fs.writeFileSync(OUT, body);
console.log(`written ${OUT} (${(body.length/1024).toFixed(1)} KB)`);
